### ISSUE TITLE
17.09: Update data_pipeline with new SO accession for trinucleotide_diseases

### ISSUE THREAD

**Issue by ckongEbi** [opentargets/data-providers-docs#35]
#### Tasks 
- [x] Update SO accession in `resources/eco_scores.tsv` with SO:0002165 trinucleotide_repeat_expansion  `https://github.com/The-Sequence-Ontology/SO-Ontologies/issues/399` before `--evs` step
- [x] EVA need to be aware new SO code to use in JSON file
- [ ] Speak to Miguel to update front-end

**Comment by ckongEbi** [comment]
@emepyc will let you know once we get new data so this hack can be removed. thanks!

**Comment by ckongEbi** [comment]
@emepyc have updated the SO code, hack can be removed, we can use the `trinucleotide_repeat_expansion` display label directly.

`https://github.com/opentargets/data_pipeline/commit/b02cf2ce2a20a8f9f68dae56503383c39d9b9217`
