### ISSUE TITLE
17.06: data_pipeline branching strategy

### ISSUE THREAD

**Issue by ckongEbi** [opentargets/data-providers-docs#37]
Post-generating `17.06` indexes, do the following to create/test `17.08` branch

#### Tasks
- [ ] 1. PR for `17.06` branch back to `master` (mostly minor configuration changes)
- [ ] 2. re-run data_pipeline from `master` , ensuring all steps are fine.
- [ ] 3. branch from `master` for `17.08`
